SCOREBOARD: #Supports more than 32 characters
  TITLE: '&6&lExample &7| &fUtils'
  CONFIG: # Use %d_arrow%, %yes%, %no%, %star%, %crown%, %sad%, %bigarrow%, %airplane% and %arrowlittle%
   - '&7&m--------------------'
   - '&eYour Name&7: &f%playername%'
   - '&eOnline&7: &f%online%'
   - '&eTps&7: &f%tps%'
   - '&eIcons&7: &f%d_arrow% %yes% %no% %star% %crown% %sad% %bigarrow% %airplane% %arrowlittle%'
   - '&d&7&m--------------------'

Tablist:
  Left:
    Line1: ' '
    Line2: '&6&lServer Info'
    Line3: ' '
    Line4: '&eTs3&7: &fts.example.com'
    Line5: '&eDiscord&7: &fexample.com/discord'
    Line6: '&eStore&7: &fstore.example.com'
    Line7: ' '
    Line8: ' '
    Line9: ' '
    Line10: ' '
    Line11: ' '
    Line12: ' '
    Line13: ' '
    Line14: ' '
    Line15: ' '
    Line16: ' '
    Line17: ' '
    Line18: ' '
    Line19: ' '
    Line20: ' '
  Middle:
    Line1: ' '
    Line2: '&6&lPlayer Info'
    Line3: ' '
    Line4: '&ePlayers&7: &f%onlinePlayers%'
    Line5: '&eYourName&7:&f %player%'
    Line6: ' '
    Line7: ' '
    Line8: ' '
    Line9: ' '
    Line10: ' '
    Line11: ' '
    Line12: ' '
    Line13: ' '
    Line14: ' '
    Line15: ' '
    Line16: ' '
    Line17: ' '
    Line18: ' '
    Line19: ' '
    Line20: ' '
  Right:
    Line1: ' '
    Line2: '&4&lWarning!'
    Line3: '&7We recommend the'
    Line4: '&7the use of &c1.7'
    Line5: '&7and not &c1.8&7.'
    Line6: ' '
    Line7: ' '
    Line8: ' '
    Line9: ' '
    Line10: ' '
    Line11: ' '
    Line12: ' '
    Line13: ' '
    Line14: ' '
    Line15: ' '
    Line16: ' '
    Line17: ' '
    Line18: ' '
    Line19: ' '
    Line20: ' '
# This plugin is open source for those who want to do it to their liking, updates will be made every day, stay tuned to GitHub